language: node_js
node_js:
- '5'
env:
  global:
  - secure: NB4FCQJuYjVbagCzFMib8AOj/lMRsY2ZftFWI/5HVd7a55Ck/Wq5QF4WVKaajZaefq6eKh7p8FG61JGvtIeqPFTM1hjGTkGfqT9Vj7eCewsmFENZiATSK4lC5j/YK4R38DeKeDHlxVN2OZJokk+AFqxinI0LMzGADq4MNvfYQ40=
before_install:
  - npm i -g grunt-cli firebase-tools
install:
  - npm install
  - npm run build
after_success:
  - firebase deploy --token=${TOKEN}
